Add contact renew
EasyGnuPG/pgpg pull request #81
Opened 2018-07-07 06:29 UTC by diveshuttam

closes #49 
Modify interact functionality a bit,
Now explicitly passing empty strings for returning None inside python script

2018-07-07 10:14 UTC, dashohoxha commented on src/cmd/contact/trust.sh
> +    call_gpg fn/interact.py "$contact" "${commands[@]}"
Here you are complicating the code by using Bash arrays, they are not the best or strongest feature of Bash. I think that it is better to pass the commands as a string (as it was done before), and you can use `commands.split("\n")` in Python to convert it to an array. I think this is cleaner.

Actually, I think that you should give only the action (for example set-trust) and the `$level` of trust as arguments. The python code should figure out the sequence of commands that needs to be sent interactively to perform the given action.

2018-07-07 10:14 UTC, dashohoxha commented on src/cmd/key/renew.sh
> +    call_gpg fn/interact.py "$GPG_KEY" "${commands[@]}"
The same comment as before here. The only argument passed here should be the `$time` of expiration (besides the action, which may be `set-expiration-time`).
Even better, you can give the `$expdate` as an argument and let the python do the calculations.

2018-07-07 10:14 UTC, dashohoxha commented on src/cmd/key/renew.sh
> +
Why don't you print this message from the Python code, if there is some error?

2018-07-09 06:44 UTC, dashohoxha requested changes

2018-07-09 06:44 UTC, dashohoxha commented on src/gpg/contact/trust.py
> +    commands = ";trust;;{level};;quit;;".format(level=level).split(";")
You can build here a list straightaway, instead of doing it with string, format and split.

2018-07-09 06:44 UTC, dashohoxha commented on src/gpg/key/renew.py
> +    commands = ";expire;;{time};;key 1;;expire;;{time};;save;;".format(
Here too you can build a list directly.

2018-07-09 08:25 UTC, dashohoxha commented on src/gpg/fn/interact.py
> +    """
I guess this is not relevant anymore, and also the corresponding code.

2018-07-10 04:27 UTC, diveshuttam commented on src/cmd/key/renew.sh
> +
@dashohoxha I was working on #83 then it occured to me that even if python script exits with a non zero status (fails), still all the further commands will still be executed in this methodology. Though it is of no harm in this particular case but there are places where I don't want them to. I have following propositions, Need your suggestions on what I should use:

- `set -e` for all python scripts (in call_gpg function) before the python call.  
- `set -e` in all the required bash scripts. just above the call gpg.
- use the earlier functionality with error messages ( `err=$? ... fail "error..."` )
- explicit source for exit (`[[ $err == 0 ]] || exit 1`) in each of the required place without printing error (error will be printed in python itself)

2018-07-10 06:41 UTC, dashohoxha commented on src/cmd/key/renew.sh
> +
In most of the cases there is no harm. In many cases the bash script may need to clean up even if the python call returns an error status. So, automatic termination of execution is not a good option.
Let the bash script check for the exit status explicitly, if needed, and do the right action. In most of the cases nothing needs to be done.

2018-07-11 07:21 UTC, diveshuttam commented
@dashohoxha Have I missed something here??

2018-07-11 08:13 UTC, dashohoxha commented
I guess that I have missed something, because I have requested a change for something that you have already done. Maybe I have been looking at an old version.

2018-07-11 08:13 UTC, dashohoxha approved these changes

2018-07-11 09:42 UTC, merged